name: Tchno
author: Night Wolf
description: Tchno is an automatically updating, easily customizable theme for Discord.

baseurl: ""

exclude:
    - README.md
    - Gemfile

plugins:
    - jekyll-redirect-from

sass:
    style: compressed
